version: "3.9"

services:
  db:
    ports:
      - "54321:5432"
  web:
    build:
      dockerfile: Dockerfile-local
    command: >
      bash -c "python3 manage.py runserver 0.0.0.0:4444"
    ports:
      - "4444:4444"