# Generated by Django 4.0.4 on 2022-04-22 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('serial', models.CharField(blank=True, max_length=255, null=True, verbose_name='serial number')),
                ('date_of_acquisition', models.DateField(blank=True, null=True, verbose_name='date of acquisition')),
                ('warranty_start', models.DateField(blank=True, null=True, verbose_name='warranty start')),
                ('warranty_finnish', models.DateField(blank=True, null=True, verbose_name='warranty finnish')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand', verbose_name='brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='category')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.label', verbose_name='label')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='location')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='inventory')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='inventory')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)),
                'abstract': False,
            },
        ),
    ]
