# Generated by Django 4.0.4 on 2022-04-22 05:54

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'verbose_name': 'brand', 'verbose_name_plural': 'brand'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'verbose_name': 'inventory', 'verbose_name_plural': 'inventories'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'verbose_name': 'label', 'verbose_name_plural': 'labels'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'get_latest_by': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_date'), descending=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), descending=True)), 'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
    ]
